// prisma/seed.ts
import { PrismaClient, ResourceCategory, ResourceStatus } from '@prisma/client'
import { cityToSlug } from '../lib/slugify'

const prisma = new PrismaClient()

const VERIFIED_BY = 'Investigación inicial'
const VERIFIED_AT = new Date('2026-06-28')

function exp(dateStr: string): Date {
  return new Date(dateStr)
}

async function main() {
  // Reset resources so re-running seed doesn't accumulate duplicates
  await prisma.resource.deleteMany({})
  await prisma.city.deleteMany({})
  await prisma.country.deleteMany({})

  // Countries — 'global' is a virtual country (active:false, never shown in selector)
  await prisma.country.createMany({
    data: [
      { slug: 'global',    nameEs: 'Global',          nameEn: 'Global',         flag: '🌐', active: false },
      { slug: 'spain',     nameEs: 'España',          nameEn: 'Spain',          namePt: 'Espanha',       flag: '🇪🇸', cca2: 'es', active: true },
      { slug: 'usa',       nameEs: 'Estados Unidos',  nameEn: 'United States',  namePt: 'Estados Unidos', flag: '🇺🇸', cca2: 'us', active: true },
      { slug: 'colombia',  nameEs: 'Colombia',        nameEn: 'Colombia',       namePt: 'Colômbia',      flag: '🇨🇴', cca2: 'co', active: true },
      { slug: 'brazil',    nameEs: 'Brasil',          nameEn: 'Brazil',         namePt: 'Brasil',        flag: '🇧🇷', cca2: 'br', active: true },
      { slug: 'argentina', nameEs: 'Argentina',       nameEn: 'Argentina',      namePt: 'Argentina',     flag: '🇦🇷', cca2: 'ar', active: true },
      { slug: 'peru',      nameEs: 'Perú',            nameEn: 'Peru',           namePt: 'Peru',          flag: '🇵🇪', cca2: 'pe', active: true },
      { slug: 'chile',     nameEs: 'Chile',           nameEn: 'Chile',          namePt: 'Chile',         flag: '🇨🇱', cca2: 'cl', active: true },
      { slug: 'mexico',    nameEs: 'México',          nameEn: 'Mexico',         namePt: 'México',        flag: '🇲🇽', cca2: 'mx', active: true },
      { slug: 'ecuador',   nameEs: 'Ecuador',         nameEn: 'Ecuador',        namePt: 'Equador',       flag: '🇪🇨', cca2: 'ec', active: true },
    ],
    skipDuplicates: true,
  })

  // Cities per country
  const cityData = [
    { countrySlug: 'spain',     nameEs: 'Madrid',          nameEn: 'Madrid',          namePt: 'Madrid' },
    { countrySlug: 'usa',       nameEs: 'Doral, FL',       nameEn: 'Doral, FL',       namePt: 'Doral, FL' },
    { countrySlug: 'usa',       nameEs: 'Miramar, FL',     nameEn: 'Miramar, FL',     namePt: 'Miramar, FL' },
    { countrySlug: 'usa',       nameEs: 'Miami (online)',  nameEn: 'Miami (online)',  namePt: 'Miami (online)' },
    { countrySlug: 'colombia',  nameEs: 'Bogotá',          nameEn: 'Bogotá',          namePt: 'Bogotá' },
    { countrySlug: 'colombia',  nameEs: 'Barranquilla',    nameEn: 'Barranquilla',    namePt: 'Barranquilla' },
    { countrySlug: 'colombia',  nameEs: 'Medellín',        nameEn: 'Medellín',        namePt: 'Medellín' },
    { countrySlug: 'colombia',  nameEs: 'Santa Marta',     nameEn: 'Santa Marta',     namePt: 'Santa Marta' },
    { countrySlug: 'colombia',  nameEs: 'Bucaramanga',     nameEn: 'Bucaramanga',     namePt: 'Bucaramanga' },
    { countrySlug: 'colombia',  nameEs: 'Cartagena',       nameEn: 'Cartagena',       namePt: 'Cartagena' },
    { countrySlug: 'argentina', nameEs: 'Buenos Aires',    nameEn: 'Buenos Aires',    namePt: 'Buenos Aires' },
    { countrySlug: 'mexico',    nameEs: 'CDMX',            nameEn: 'Mexico City',     namePt: 'Cidade do México' },
    { countrySlug: 'ecuador',   nameEs: 'Quito',           nameEn: 'Quito',           namePt: 'Quito' },
    { countrySlug: 'ecuador',   nameEs: 'Guayaquil',       nameEn: 'Guayaquil',       namePt: 'Guayaquil' },
    { countrySlug: 'peru',      nameEs: 'Lima',            nameEn: 'Lima',            namePt: 'Lima' },
    { countrySlug: 'chile',     nameEs: 'Santiago',        nameEn: 'Santiago',        namePt: 'Santiago' },
    { countrySlug: 'chile',     nameEs: 'Temuco',          nameEn: 'Temuco',          namePt: 'Temuco' },
    { countrySlug: 'chile',     nameEs: 'Calama',          nameEn: 'Calama',          namePt: 'Calama' },
  ]

  const createdCities = await Promise.all(
    cityData.map(({ countrySlug, nameEs, nameEn, namePt }) =>
      prisma.city.create({
        data: { countrySlug, slug: cityToSlug(nameEs), nameEs, nameEn, namePt },
      })
    )
  )

  // Build lookup: "countrySlug::nameEs" → cityId
  const cityMap = Object.fromEntries(
    createdCities.map((c) => [`${c.countrySlug}::${c.nameEs}`, c.id])
  )

  // GLOBAL resources (shown on every country page)
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'global',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Venezuela Te Busca',
        url: 'https://venezuelatebusca.com',
        free: true,
        notesEs: 'Base de datos centralizada con +50.000 reportes. Busca por nombre o cédula desde cualquier país.',
        notesEn: 'Centralized database with 50k+ reports. Search by name or ID number from any country.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Desaparecidos Terremoto Venezuela',
        url: 'https://desaparecidosterremotovenezuela.com',
        free: true,
        notesEs: 'Portal ciudadano con +58.000 reportes. Busca por nombre, cédula o apellido. Disponible desde cualquier país.',
        notesEn: 'Citizen portal with 58k+ reports. Search by name, ID or surname. Available from any country.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Terremoto Venezuela — mapa colaborativo de daños',
        url: 'https://terremotovenezuela.com',
        free: true,
        notesEs: 'Mapa colaborativo donde personas reportan y consultan fotos de daños en calles y edificios de Venezuela. Útil para verificar estado de zonas específicas.',
        notesEn: 'Collaborative map where people report and view photos of structural damage across Venezuela. Useful for verifying status of specific areas.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Venezuela Reporta — buscador unificado de desaparecidos',
        url: 'https://venezuelareporta.org',
        free: true,
        notesEs: 'Agrega y deduplica reportes de múltiples plataformas: 86.984 reportes totales, 34.713 duplicados eliminados, 46.044 sin localizar, 5.653 encontradas. También tiene mapa de emergencia, recursos y modo campo para voluntarios. Actualizado en tiempo real.',
        notesEn: 'Aggregates and deduplicates reports from multiple platforms: 86,984 total reports, 34,713 duplicates removed, 46,044 still missing, 5,653 found. Also has emergency map, resource directory and field mode for volunteers. Updated in real time.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'UNICEF — Fondo Emergencia Venezuela',
        url: 'https://unicef.org',
        free: false,
        notesEs: 'Agencia ONU para la infancia. Appeal dedicado al sismo del 24-jun-2026. Estima necesitar $52M. Donaciones aceptadas desde cualquier país vía web local de UNICEF.',
        notesEn: "UN children's agency. Dedicated earthquake appeal. Estimated $52M needed. Donations accepted from any country via local UNICEF website.",
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Cáritas Internationalis — Venezuela',
        url: 'https://donate.caritas.org/venezuela/',
        free: false,
        notesEs: 'Red Cáritas desplegada en Venezuela desde el 25-jun. Canal de donación internacional activo con IBAN para transferencias y opción online. Fundada 1997, presencia territorial real.',
        notesEn: 'Caritas network deployed in Venezuela since Jun 25. Active international donation channel with IBAN and online option. Founded 1997, real territorial presence.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'International Rescue Committee (IRC)',
        url: 'https://rescue.org',
        free: false,
        notesEs: '90+ años de experiencia humanitaria. Equipos en terreno en Venezuela entregando salud, agua, nutrición y protección. Máximas calificaciones en Charity Navigator.',
        notesEn: '90+ years of humanitarian experience. Teams on ground in Venezuela delivering health, water, nutrition and protection. Top-rated by Charity Navigator.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'GlobalGiving — Venezuela Earthquake Relief Fund',
        url: 'https://globalgiving.org/projects/venezuela-earthquake-relief-fund',
        free: false,
        notesEs: 'Canaliza donaciones a ONGs locales verificadas. Donaciones en USD desde cualquier país.',
        notesEn: 'Channels donations to vetted local NGOs. Donations in USD from any country.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Direct Relief — Venezuela',
        url: 'https://directrelief.org',
        free: false,
        notesEs: '100% de donaciones designadas a Venezuela van a esa respuesta. Activos en Venezuela con historial verificado.',
        notesEn: '100% of Venezuela-designated donations go to that response. Active in Venezuela with verified track record.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_MONEY,
        name: 'World Central Kitchen — Venezuela',
        url: 'https://wck.org',
        free: false,
        notesEs: 'Fundación del chef José Andrés. Desplegados en Venezuela distribuyendo comidas. Fondo dedicado al terremoto activo en wck.org.',
        notesEn: 'Chef José Andrés foundation. Deployed in Venezuela distributing meals. Dedicated earthquake fund active at wck.org.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.MENTAL_HEALTH,
        name: 'PsicoLínea Venezuela (apoyo desde exterior)',
        phone: '0414-121 78 82 / 0424-172 39 81',
        free: true,
        notesEs: 'Canal de asistencia psicológica gratuita operado desde Venezuela. Accesible por llamada internacional para quien tenga familia allá y necesite orientación.',
        notesEn: 'Free psychological support channel operated from Venezuela. Accessible by international call for diaspora members needing guidance.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_PHYSICALLY,
        name: 'Ayuda por Venezuela — directorio de centros de acopio',
        url: 'https://ayudaparavenezuela.com',
        free: true,
        notesEs: 'Directorio ciudadano con 423+ centros de acopio activos en Venezuela, Colombia y España. Filtra por país, estado y tipo de insumos (agua, alimentos, medicinas, ropa, bebés). Actualizado en tiempo real por voluntarios.',
        notesEn: '423+ active collection centers in Venezuela, Colombia and Spain. Filter by country, state and supply type (water, food, medicine, clothing, baby supplies). Updated in real time by volunteers.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'global',
        category: ResourceCategory.DONATE_PHYSICALLY,
        name: 'Venezuela Resiste — mapa de acopios y refugios',
        url: 'https://acopios-refugios.vercel.app',
        free: true,
        notesEs: 'Mapa colaborativo en tiempo real con centros de acopio y refugios disponibles en Venezuela. Cubre todos los estados. Los acopios se publican de inmediato; los refugios se revisan antes de publicar.',
        notesEn: 'Real-time collaborative map of supply centers and available shelters across all Venezuelan states. Supply centers publish immediately; shelters are reviewed before publication.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
    ],
  })

  // SPAIN
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'spain',
        category: ResourceCategory.CALL_FREE,
        name: 'Movistar / O2 — llamadas y SMS gratis a Venezuela',
        url: 'https://www.movistar.es',
        free: true,
        notesEs: 'Movistar y O2 (Telefónica) ofrecen llamadas y SMS gratuitos desde España a Venezuela mientras dure la emergencia. Sin fecha de corte declarada. Solo clientes de contrato.',
        notesEn: 'Movistar and O2 (Telefónica) offer free calls and SMS from Spain to Venezuela for the duration of the emergency. No declared end date. Contract customers only.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.CALL_FREE,
        name: 'MasOrange — llamadas, SMS y roaming gratis a Venezuela',
        url: 'https://blog.masorange.es',
        free: true,
        notesEs: 'MasOrange (Orange, Simyo, Amena, Guuk) ofrece llamadas y SMS gratuitos desde España a Venezuela, más roaming gratuito para clientes en Venezuela. Activo mientras sea necesario. Solo clientes de contrato.',
        notesEn: 'MasOrange (Orange, Simyo, Amena, Guuk) offers free calls and SMS from Spain to Venezuela, plus free roaming for customers in Venezuela. Active as long as needed. Contract customers only.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Cáritas Española — Bizum Venezuela',
        url: 'https://www.caritas.es',
        bizum: '0089',
        free: false,
        notesEs: 'Bizum al 0089. Movilizó 300.000€ para Venezuela. Canal verificado por Revista Haz y medios nacionales.',
        notesEn: 'Bizum to 0089. Mobilized €300k for Venezuela. Verified by Revista Haz and national media.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'World Central Kitchen — Bizum',
        url: 'https://wck.org',
        bizum: '03843',
        free: false,
        notesEs: 'Bizum al 03843. Fundación del chef José Andrés. Desplegados en Venezuela distribuyendo comidas.',
        notesEn: 'Donate via Bizum 03843. Chef José Andrés foundation. Deployed in Venezuela distributing meals.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'I Love Venezuela Foundation — GoFundMe',
        url: 'https://gofundme.com/f/emergency-relief-for-venezuela-earthquake-victims',
        free: false,
        notesEs: 'Nombre oficial: I Love Venezuela Foundation. Aliada de GEM. Campaña activa y promovida por GoFundMe oficial en X. URL activo verificado.',
        notesEn: 'Official name: I Love Venezuela Foundation. GEM partner. Active campaign promoted by official GoFundMe on X. Verified active URL.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Save the Children España — Venezuela',
        url: 'https://www.savethechildren.es/donacion-ong/terremoto-en-venezuela-2026',
        bizum: '13132',
        phone: '900 37 37 15',
        free: false,
        notesEs: 'Bizum al 13132 (concepto: Terremoto Venezuela). Tel gratuito 900 37 37 15 lun–vie 9–21h. También transferencia a Santander, CaixaBank o BBVA (ver web).',
        notesEn: 'Bizum to 13132 (ref: Terremoto Venezuela). Free phone 900 37 37 15 Mon–Fri 9am–9pm. Also bank transfer (see website).',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Médicos Sin Fronteras — Fondo de Emergencias Venezuela',
        url: 'https://www.msf.es',
        free: false,
        notesEs: 'MSF activó su Fondo de Emergencias para Venezuela. Donaciones en msf.es.',
        notesEn: 'MSF activated its Emergency Fund for Venezuela. Donations at msf.es.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Fundación Chamos España — emergencia Venezuela',
        url: 'https://fundacionchamos.es',
        free: false,
        notesEs: 'Delegación española de Chamos — In Aid of the Children of Venezuela. Fundada 2007 (UK), 2020 (ES). Distribución activa en Venezuela. Donaciones en web.',
        notesEn: 'Spanish branch of Chamos — In Aid of the Children of Venezuela. Founded 2007 (UK), 2020 (Spain). Active distribution in Venezuela.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['spain::Madrid'],
        name: 'Madrid — Refugiados Sin Fronteras / Diáspora en Movimiento',
        address: 'Calle Matilde Landa 26',
        schedule: 'Sáb 27 y dom 28 junio, 11:00–18:00h',
        free: true,
        notesEs: 'Calle Matilde Landa 26, Madrid. Sáb 27 y dom 28 junio, 11:00–18:00h.',
        notesEn: 'Calle Matilde Landa 26, Madrid. Sat Jun 27 & Sun Jun 28, 11am–6pm.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'spain',
        category: ResourceCategory.MENTAL_HEALTH,
        name: 'Teléfono de la Esperanza',
        url: 'https://telefonodelaesperanza.org',
        phone: '717 003 717',
        schedule: '24h',
        free: true,
        notesEs: 'Atención psicológica gratuita 24 horas en España. Atiende crisis emocionales y duelo.',
        notesEn: 'Free 24h psychological support in Spain. Handles emotional crises and grief.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
    ],
  })

  // USA
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_MONEY,
        cityId: cityMap['usa::Doral, FL'],
        name: 'Global Empowerment Mission (GEM)',
        url: 'https://gemusa.org',
        free: false,
        notesEs: 'Sede en Doral, FL. Desplegados activamente en Venezuela. Historial verificado desde 2018. Aliado de I Love Venezuela Foundation.',
        notesEn: 'Based in Doral, FL. Actively deployed in Venezuela. Verified track record since 2018. I Love Venezuela Foundation partner.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_MONEY,
        cityId: cityMap['usa::Doral, FL'],
        name: 'VACC Foundation — Cámara Venezolana-Americana',
        url: 'https://vaccfoundation.org',
        free: false,
        notesEs: 'ONGs de empresas venezolanas en Doral. Fondos para logística y distribución en Venezuela.',
        notesEn: 'Venezuelan-American business NGO in Doral. Funds for logistics and distribution in Venezuela.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_MONEY,
        name: 'GlobalGiving — Venezuela Earthquake Relief Fund',
        url: 'https://globalgiving.org/projects/venezuela-earthquake-relief-fund',
        free: false,
        notesEs: 'Canaliza a múltiples ONGs verificadas incluyendo UNICEF USA y Save the Children.',
        notesEn: 'Channels to multiple vetted NGOs including UNICEF USA and Save the Children.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Direct Relief — Venezuela',
        url: 'https://directrelief.org',
        free: false,
        notesEs: '100% de donaciones designadas para Venezuela van exclusivamente a esa respuesta.',
        notesEn: '100% of donations designated for Venezuela go exclusively to that response.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['usa::Doral, FL'],
        name: 'Miami — GEM Doral (centro principal)',
        url: 'https://gemusa.org',
        address: '1850 NW 84th Avenue, Suite 100, Doral FL 33126',
        schedule: 'Lun–Dom, verificar horario en gemusa.org',
        free: true,
        notesEs: 'GEM Doral: 1850 NW 84th Ave, Suite 100. También acepta voluntarios. Centro principal de distribución a Venezuela.',
        notesEn: 'GEM Doral: 1850 NW 84th Ave, Suite 100. Also accepts volunteers. Main distribution center to Venezuela.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['usa::Miramar, FL'],
        name: 'Miami — All Star Training Center',
        address: '11820 Miramar Pkwy Suite 2',
        schedule: '8:30am–8pm',
        free: true,
        notesEs: 'Recibe donaciones 26 jun – 3 jul, 8:30am–8pm. Alimentos, medicinas, agua, higiene.',
        notesEn: 'Accepting donations Jun 26 – Jul 3, 8:30am–8pm. Food, medicine, water, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['usa::Doral, FL'],
        name: 'Miami — Nu Stadium (Inter Miami CF + GEM)',
        address: 'Nu Stadium',
        schedule: '9am–3pm',
        free: true,
        notesEs: 'Recolección 26 jun – 3 jul, 9am–3pm. También durante concierto Carín León 28 jun 6–8:30pm.',
        notesEn: 'Collection Jun 26 – Jul 3, 9am–3pm. Also during Carín León concert Jun 28, 6–8:30pm.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'usa',
        category: ResourceCategory.MENTAL_HEALTH,
        cityId: cityMap['usa::Miami (online)'],
        name: "Children's Bereavement Center / Lift from Loss",
        url: 'https://childbereavement.org',
        free: true,
        notesEs: 'Apoyo psicológico gratuito en español e inglés para afectados en Venezuela y la diáspora. Online.',
        notesEn: 'Free bereavement counseling in Spanish and English for those impacted in Venezuela and diaspora. Online.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
    ],
  })

  // COLOMBIA
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Corporación Presentes',
        url: 'https://presentes.co/dona/',
        free: false,
        notesEs: 'Organización con presencia local. Canal verificado para donaciones.',
        notesEn: 'Organization with local presence. Verified donation channel.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Bancos de Alimentos Colombia (Abaco)',
        free: false,
        notesEs: 'Asociación de Bancos de Alimentos de Colombia. Transferencia Bre-B Bancolombia: 0090989753',
        notesEn: 'Colombian Food Bank Association. Bancolombia Bre-B transfer: 0090989753',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Catholic Relief Services (CRS) — Venezuela',
        url: 'https://www.crs.org/donate/venezuela-earthquake',
        free: false,
        notesEs: 'CRS trabaja con Cáritas Venezuela entregando refugio, comida, agua y atención médica. Donaciones en crs.org. Recomendado por CNN y Billboard.',
        notesEn: 'CRS works with Caritas Venezuela delivering shelter, food, water and medical care. Donate at crs.org. Recommended by CNN and Billboard.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Bogotá'],
        name: 'Bogotá — Fundación Juntos se Puede (Chapinero 1)',
        address: 'Kr 13 #63-21, local 111, Hotel Matisse, Chapinero',
        schedule: 'Lun–Dom 7am–6pm',
        free: true,
        notesEs: 'Lun–Dom 7am–6pm hasta 1 julio. Agua, alimentos, medicinas, higiene, ropa.',
        notesEn: 'Mon–Sun 7am–6pm until Jul 1. Water, food, medicine, hygiene, clothing.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Bogotá'],
        name: 'Bogotá — Fundación Juntos se Puede (Chapinero 2)',
        address: 'Kr 9 #61-70, Chapinero',
        schedule: 'Lun–Dom 9am–7pm',
        free: true,
        notesEs: 'Lun–Dom 9am–7pm. Agua, alimentos no perecederos, medicinas, higiene.',
        notesEn: 'Mon–Sun 9am–7pm. Water, non-perishables, medicine, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Bogotá'],
        name: 'Bogotá — Calle 104 Pasadena (Suba)',
        address: 'Calle 104 #54-31, barrio Pasadena, Suba',
        schedule: 'Lun–Dom 7am–6pm',
        free: true,
        notesEs: 'Lun–Dom 7am–6pm hasta 1 julio. Principal centro de la Fundación Juntos se Puede.',
        notesEn: 'Mon–Sun 7am–6pm until Jul 1. Main Fundación Juntos se Puede center.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-02'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Barranquilla'],
        name: 'Barranquilla — Alcaldía (Barranquillita)',
        address: 'Carrera 43 #6-120, Barranquillita',
        schedule: 'Lun–Dom 8am–4pm',
        free: true,
        notesEs: 'Lun–Dom 8am–4pm. Agua, alimentos, medicamentos, ropa, colchones, aseo.',
        notesEn: 'Mon–Sun 8am–4pm. Water, food, medicine, clothing, mattresses, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Medellín'],
        name: 'Medellín — Laika Arkadia',
        address: 'Cra. 70 #1-141, local 9822',
        free: true,
        notesEs: 'Recibe insumos para mascotas y familias damnificadas.',
        notesEn: 'Accepts supplies for pets and affected families.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Santa Marta'],
        name: 'Santa Marta — Parque La Tenería',
        address: 'Carrera 2 con 1D36, cerca Playa Los Cocos',
        schedule: '7am–6pm',
        free: true,
        notesEs: 'Lun–Dom 7am–6pm. Alimentos, medicinas, agua, higiene.',
        notesEn: 'Mon–Sun 7am–6pm. Food, medicine, water, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Bucaramanga'],
        name: 'Centro de Acopio Bucaramanga',
        address: 'Calle 18 #21-52, San Francisco, diagonal Iglesia San Francisco',
        schedule: '7am–7pm',
        free: true,
        notesEs: 'Lun–Dom 7am–7pm. Alimentos, medicinas, agua, higiene.',
        notesEn: 'Mon–Sun 7am–7pm. Food, medicine, water, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Cartagena'],
        name: 'Centro Intégrate Cartagena',
        address: 'Carrera 49 #31B-125, barrio Líbano',
        schedule: '8am–4pm',
        free: true,
        notesEs: 'Lun–Dom 8am–4pm. Alimentos no perecederos, agua, productos de aseo.',
        notesEn: 'Mon–Sun 8am–4pm. Non-perishables, water, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['colombia::Medellín'],
        name: 'Medellín — I.E. Héctor Abad Gómez (Placita de Flores)',
        address: 'Calle 50 #39-65, Placita de Flores',
        schedule: '8am–5pm',
        free: true,
        notesEs: 'Operación Todos con Venezuela. Lun–Dom 8am–5pm. Agua, alimentos, insumos médicos, ropa.',
        notesEn: 'Operation Todos con Venezuela. Mon–Sun 8am–5pm. Water, food, medical supplies, clothing.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.MENTAL_HEALTH,
        cityId: cityMap['colombia::Medellín'],
        name: 'Centro Intégrate Medellín',
        address: 'Carrera 49 #58-40, barrio Prado',
        schedule: 'Lun–Vie 8am–4pm',
        free: true,
        notesEs: 'Apoyo psicosocial gratuito para personas emocionalmente afectadas.',
        notesEn: 'Free psychosocial support for emotionally affected people. Mon–Fri 8am–4pm.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'colombia',
        category: ResourceCategory.MENTAL_HEALTH,
        name: 'Línea 106 — Salud Mental Colombia',
        phone: '106',
        schedule: '24h',
        free: true,
        notesEs: 'Línea gratuita 24h para crisis emocionales. Disponible en todo Colombia.',
        notesEn: 'Free 24h line for emotional crises. Available throughout Colombia.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
    ],
  })

  // ARGENTINA
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'argentina',
        category: ResourceCategory.FIND_FAMILY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Cancillería Argentina — argentinos en Venezuela',
        phone: 'WhatsApp: +5491150615903 | Voz: +5491150407243',
        free: true,
        notesEs: 'Para ciudadanos argentinos en Venezuela sin contacto. Correos: diare@mrecic.gov.ar / consular_evene@mrecic.gov.ar',
        notesEn: 'For Argentine citizens in Venezuela without contact. Emails: diare@mrecic.gov.ar / consular_evene@mrecic.gov.ar',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_MONEY,
        name: 'ACNUR — donación internacional',
        url: 'https://donacion.fundacionacnur.org/venezuela/',
        free: false,
        notesEs: 'URL específico para Venezuela activo. ACNUR Argentina ofrece triplicar donaciones mensuales hasta el 30 de junio. Donaciones en pesos.',
        notesEn: 'Venezuela-specific URL active. ACNUR Argentina tripling monthly donations until June 30. Donations in pesos.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Buenos Aires — Casa Venezuela Arg',
        address: 'Combate de los Pozos 1055, San Cristóbal / Monserrat, CABA',
        free: true,
        notesEs: 'Centro de acopio confirmado activo. Recibe donaciones físicas. Recomienda también donar vía ACNUR. Verificar si sigue abierto — reportes de alta demanda.',
        notesEn: 'Confirmed active collection center. Accepts physical donations. Also recommends donating via ACNUR. Verify if still open — high demand reported.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Hipólita — Palermo',
        address: 'Humboldt 2474, Palermo, CABA',
        free: true,
        notesEs: 'Restaurante venezolano. Punto de acopio comunitario confirmado.',
        notesEn: 'Venezuelan restaurant. Confirmed community collection point.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Artigiani — Colegiales',
        address: 'Ciudad de la Paz 572, Colegiales, CABA',
        free: true,
        notesEs: 'Panificadora venezolana. Punto de acopio confirmado.',
        notesEn: 'Venezuelan bakery. Confirmed collection point.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Prados Café — Colegiales',
        address: 'Moldes 1379, Colegiales, CABA',
        free: true,
        notesEs: 'Café venezolano. Punto de acopio confirmado.',
        notesEn: 'Venezuelan café. Confirmed collection point.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'Vanshelato — Coghlan y Villa Pueyrredón',
        address: 'Iberá 3799 (Coghlan) y Griveo 2532 (Villa Pueyrredón), CABA',
        free: true,
        notesEs: 'Dos locales en CABA. También Laprida 901, Lomas de Zamora.',
        notesEn: 'Two locations in CABA. Also Laprida 901, Lomas de Zamora.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'argentina',
        category: ResourceCategory.MENTAL_HEALTH,
        cityId: cityMap['argentina::Buenos Aires'],
        name: 'AASM — apoyo psicológico gratuito venezolanos',
        schedule: 'Lun–Vie',
        free: true,
        notesEs: 'Asociación Argentina de Salud Mental. Espacio gratuito de escucha y acompañamiento para venezolanos en Argentina afectados por el sismo.',
        notesEn: 'Argentine Mental Health Association. Free listening and support space for Venezuelans in Argentina affected by the earthquake.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // MEXICO
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'mexico',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['mexico::CDMX'],
        name: 'CDMX — Brigada Topos Tlatelolco (Iztapalapa)',
        address: 'Magistrados 75, Amp. El Sifón, Iztapalapa, 09180',
        free: true,
        notesEs: 'Centro de acopio para insumos humanitarios y herramientas para rescatistas. Cascos, guantes, botas, palas.',
        notesEn: 'Collection point for humanitarian supplies and rescue equipment. Helmets, gloves, boots, shovels.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'mexico',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['mexico::CDMX'],
        name: 'CDMX — Pasticho Express (Parques Polanco)',
        address: 'Centro Comercial Parques Polanco',
        free: true,
        notesEs: 'Centro de Acopio Solidario. Restaurante venezolano. Alimentos, medicinas, agua, higiene.',
        notesEn: 'Solidarity Collection Center. Venezuelan restaurant. Food, medicine, water, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // ECUADOR
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'ecuador',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['ecuador::Quito'],
        name: 'Quito — IMPAQTO La Carolina',
        address: 'Edificio IQON, Av. Shyris y Av. Suecia',
        schedule: '9am–6pm',
        free: true,
        notesEs: 'Lun–Dom 9am–6pm. Cámara de Comercio Venezolano-Ecuatoriana. Alimentos y medicinas.',
        notesEn: 'Mon–Sun 9am–6pm. Venezuelan-Ecuadorian Chamber of Commerce. Food and medicine.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'ecuador',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['ecuador::Quito'],
        name: 'Quito — Cachapas El Félix',
        address: 'Av. Naciones Unidas y 10 de Agosto',
        free: true,
        notesEs: 'Punto de recepción de donaciones. Alimentos y medicinas.',
        notesEn: 'Donation drop-off point. Food and medicine.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'ecuador',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['ecuador::Guayaquil'],
        name: 'Guayaquil — Comando con Venezuela (Urdesa)',
        address: 'Av. Víctor Emilio Estrada y Las Jiguas (ref. Chamos Burger)',
        schedule: '9am–6pm',
        free: true,
        notesEs: 'Lun–Dom 9am–6pm. Solo alimentos no perecederos y medicamentos.',
        notesEn: 'Mon–Sun 9am–6pm. Non-perishables and medicine only — no water or clothing.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // PERU
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'peru',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['peru::Lima'],
        name: 'Lima — Embajada de Venezuela (exteriores)',
        address: 'Embajada de Venezuela, Cercado de Lima',
        free: true,
        notesEs: 'Iniciativa comunitaria en exteriores de la embajada. Medicinas, ropa, alimentos no perecederos.',
        notesEn: 'Community initiative outside Venezuelan embassy. Medicine, clothing, non-perishables.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'peru',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['peru::Lima'],
        name: 'Lima — Parque Voces por el Clima',
        address: 'Parque Voces por el Clima, Santiago de Surco',
        free: true,
        notesEs: 'Centro de acopio principal. Ciudadanía Sin Fronteras coordina envío a Venezuela. Proceso puede durar 6–8 meses.',
        notesEn: 'Main collection center. Ciudadanía Sin Fronteras coordinates shipment to Venezuela.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // CHILE
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'chile',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Desaparecidos Terremoto Venezuela — desde Chile',
        url: 'https://desaparecidosterremotovenezuela.com',
        free: true,
        notesEs: 'Portal ciudadano accesible desde Chile. Busca por nombre o cédula. +58.000 reportes activos.',
        notesEn: 'Citizen portal accessible from Chile. Search by name or ID. 58k+ active reports.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_MONEY,
        name: 'Cáritas Venezuela — donación desde Chile',
        url: 'https://caritasvenezuela.org/donaciones',
        free: false,
        notesEs: 'Canal de donación internacional directo a Cáritas Venezuela. Verificado por T13 como opción desde Chile. Red con presencia territorial desde 1997.',
        notesEn: 'International donation channel direct to Caritas Venezuela. Verified by T13 as option from Chile. Network with territorial presence since 1997.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_MONEY,
        name: 'ACNUR — donación desde Chile',
        url: 'https://acnur.org',
        free: false,
        notesEs: 'ACNUR activo para Venezuela. Donaciones aceptadas desde Chile vía acnur.org. Verificado por T13 como canal oficial.',
        notesEn: 'UNHCR active for Venezuela. Donations accepted from Chile via acnur.org. Verified by T13 as official channel.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Santiago'],
        name: 'Santiago — Centro de Acopio Municipal Independencia',
        address: 'Municipalidad de Independencia, Santiago',
        free: true,
        notesEs: 'Punto de acopio municipal coordinado por funcionaria de la Municipalidad de Independencia. Alimentos, medicinas, linternas, baterías.',
        notesEn: 'Municipal collection point coordinated by staff from Municipalidad de Independencia. Food, medicine, flashlights, batteries.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Temuco'],
        name: 'Temuco — Las Mil Bendiciones',
        address: 'Arquímedes 01885, Temuco',
        free: true,
        notesEs: 'Agrupación Social y Cultural de Venezolanos en La Araucanía. Alimentos no perecederos, medicamentos, linternas, baterías. Envío coordinado a Santiago.',
        notesEn: 'Venezuelan community association in La Araucanía. Non-perishables, medicine, flashlights, batteries. Coordinated shipping to Santiago.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Temuco'],
        name: 'Temuco — Venemarket',
        address: 'Los Pablos 1999, Temuco',
        free: true,
        notesEs: 'Punto de acopio de la Agrupación de Venezolanos en La Araucanía. Alimentos, medicamentos, linternas, baterías.',
        notesEn: 'Collection point by Venezuelan Association in La Araucanía. Food, medicine, flashlights, batteries.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Temuco'],
        name: 'Temuco — Sabe Venezuela',
        address: 'Luis Durand 01635, Local 1, Temuco',
        free: true,
        notesEs: 'Punto de acopio de la Agrupación de Venezolanos en La Araucanía. Alimentos, medicamentos.',
        notesEn: 'Collection point by Venezuelan Association in La Araucanía. Food and medicine.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Calama'],
        name: 'Calama — AJ Dorada Restaurant',
        address: 'Abaroa 2046, Calama',
        free: true,
        notesEs: 'Punto de acopio hasta llenar camión para envío a Santiago. Alimentos, medicinas, higiene.',
        notesEn: 'Collection point until truck is full for shipment to Santiago. Food, medicine, hygiene.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Calama'],
        name: 'Calama — Llanero Carnes al Barril',
        address: 'Emilio Sotomayor 1806, Calama',
        free: true,
        notesEs: 'Punto de acopio hasta llenar camión para envío a Santiago.',
        notesEn: 'Collection point until truck is full for shipment to Santiago.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'chile',
        category: ResourceCategory.DONATE_PHYSICALLY,
        cityId: cityMap['chile::Calama'],
        name: 'Calama — Redlogistic Market',
        address: 'Pasaje Monseñor Juan Bautista Herrada 1632, local 3, Calama',
        free: true,
        notesEs: 'Punto de acopio hasta llenar camión para envío a Santiago.',
        notesEn: 'Collection point until truck is full for shipment to Santiago.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // BRAZIL
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        countrySlug: 'brazil',
        category: ResourceCategory.FIND_FAMILY,
        name: 'Venezuela Te Busca — Brasil',
        url: 'https://venezuelatebusca.com',
        free: true,
        notesEs: 'Plataforma accesible desde Brasil. Comunidad venezolana concentrada en Boa Vista (RR) y Manaus (AM). Busca por nombre o cédula venezolana.',
        notesEn: 'Platform accessible from Brazil. Venezuelan community concentrated in Boa Vista (RR) and Manaus (AM). Search by name or Venezuelan ID.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
      },
      {
        countrySlug: 'brazil',
        category: ResourceCategory.DONATE_MONEY,
        name: 'ACNUR Brasil — emergência Venezuela',
        url: 'https://www.acnur.org/brazil',
        free: false,
        notesEs: 'ACNUR Brasil activo para Venezuela. Donaciones online en reales. Canal ONU verificado.',
        notesEn: 'UNHCR Brazil active for Venezuela. Online donations in reais. Verified UN channel.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
      {
        countrySlug: 'brazil',
        category: ResourceCategory.DONATE_MONEY,
        name: 'UNICEF Brasil — emergência Venezuela',
        url: 'https://www.unicef.org/brazil',
        free: false,
        notesEs: 'UNICEF Brasil aceita donaciones para Venezuela. 3,9 millones de niños afectados en zonas de impacto. Canal ONU verificado.',
        notesEn: 'UNICEF Brazil accepts donations for Venezuela. 3.9 million children affected in impact zones. Verified UN channel.',
        status: ResourceStatus.PUBLISHED,
        verifiedAt: VERIFIED_AT,
        verifiedBy: VERIFIED_BY,
        expiresAt: exp('2026-07-03'),
      },
    ],
  })

  // Admin user
  const adminEmail = process.env.ADMIN_EMAIL
  if (adminEmail) {
    await prisma.user.upsert({
      where: { email: adminEmail },
      update: {},
      create: { email: adminEmail, role: 'ADMIN', isActive: true },
    })
  }

  console.log('Seed complete.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
